version: '3'

services:
  account-service:
    image: rafaalberto17/account-service:1.0.0
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    user: root
    command: [ "--config.file=/prometheus-config/prometheus.yml" ]
    volumes:
      - ./prometheus-config:/prometheus-config
      - ./data/prometheus:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    user: root
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  default:
    external:
      name: app-network