version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    user: root
    command: ["--config.file=/prometheus-config/prometheus.yml"]
    volumes:
      - ./prometheus-config:/prometheus-config
      - ./data/prometheus:/prometheus
    ports:
      - "9090:9090"